routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/','PagesController@getHome');

Route::get('/about','PagesController@getAbout');

Route::get('/contact','PagesController@getContact');

Route::post('/contact/submit','MessagesController@getAbout');

Route::get('/messages','MessagesController@getMessages');


Route::resource('users','UserController');
//Route::resource('company','CompaniesController');
Route::resource('company_categories.companies','CompaniesController');
Route::resource('CompanyCategories','CompanyCategoriesController');

Route::resource('companies.managers','ManagerController');
//Route::resource('companies.coupons','CompanyCouponsController');
//Route::resource('company/{{id}}/coupons/{{couponId}}','CompanyCouponsController');
Route::get('/forms','FormsController@returnForm');

Route::resource('coupons','CouponController');


Route::get('/EbayProducts','EbayController@getProducts');

resources/views/Categories/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="formWrapper">
        <div class="row DirectionRtl">
            <div class="col-lg-12">
                <h1 class="page-header">הוספת קופון חדש</h1>
            </div>
            <!-- /.col-lg-12 -->
        </div>
        <!-- /.row -->
        <div class="row DirectionRtl" >
            <div class="col-lg-12">
                <div class="panel panel-default" >
                    <div class="panel-heading " >
                        עדכן קופון חדש
                    </div>
                    <div class="panel-body ">
                        <div class="row ">
                            <div class="col-lg-12">
                                <form role="form" action="{{route('companies.coupons.store' , $Company)}}" method="post" >
                                        <div class="row">
                                        <div class="col-lg-6">
                                            <div class="form-group">
                                                <label>תיאור הקופון11</label>
                                                <input class="form-control" value="" name="title">
                                            </div>
                                        </div>
                                        <div class="col-lg-6">
                                            <div class="form-group">
                                                <label>מחיר הקופון</label>
                                                <input class="form-control" value="" name="price">
                                            </div>
                                        </div>
                                    </div>

                                    <div class="row">
                                        <div class="col-lg-6">
                                            <div class="form-group">
                                                <label>תיאור על הקופון</label>
                                                <input class="form-control" value="" name="description">
                                            </div>
                                        </div>
                                        <div class="col-lg-6">
                                            <div class="form-group">
                                                <label>כמות קופונים קיימת</label>
                                                <input class="form-control" value="" name="quantity">
                                            </div>
                                        </div>

                                    </div>


                                    <button type="submit" class="btn btn-default DirectionLtr" style="float:left; width: 120px; text-align: center !important;" >שלח קופון</button>
                                    {{csrf_field()}}
                                </form>
                            </div>
                            <!-- /.col-lg-6 (nested) -->
                        </div>
                        <!-- /.row (nested) -->
                    </div>
                    <!-- /.panel-body -->
                </div>
                <!-- /.panel -->
            </div>
            <!-- /.col-lg-12 -->
        </div>
        <!-- /.row -->
    </div>
    <!-- /#page-wrapper -->

    </div>
    <!-- /#wrapper -->

@endsection

resources/views/Categories/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="formWrapper">
        <div class="row DirectionRtl">
            <div class="col-lg-12">
                <h1 class="page-header">הוספת קופון חדש</h1>
            </div>
            <!-- /.col-lg-12 -->
        </div>
        <!-- /.row -->
        <div class="row DirectionRtl" >
            <div class="col-lg-12">
                <div class="panel panel-default" >
                    <div class="panel-heading " >
                        עדכן קופון חדש
                    </div>
                    <div class="panel-body ">
                        <div class="row ">
                            <div class="col-lg-12">
                                <form role="form" action="{!! action('UserController@update', ['id' => $coupon->id ] ) !!}"  method="post" >


                                    <input name="_method" type="hidden" value="PATCH" >
                                    <div class="row">
                                        <div class="col-lg-6">
                                            <div class="form-group">
                                                <label>כותרת הקופון</label>
                                                <input class="form-control" value="{{$coupon->title}}" name="title">
                                            </div>
                                        </div>
                                        <div class="col-lg-6">
                                            <div class="form-group">
                                                <label>מחיר הקופון</label>
                                                <input class="form-control" value="{{$coupon->price}}" name="price">
                                            </div>
                                        </div>
                                    </div>

                                    <div class="row">
                                        <div class="col-lg-6">
                                            <div class="form-group">
                                                <label>תיאור על הקופון</label>
                                                <input class="form-control" value="{{$coupon->description}}" name="description">
                                            </div>
                                        </div>
                                        <div class="col-lg-6">
                                            <div class="form-group">
                                                <label>כמות קופונים קיימת</label>
                                                <input class="form-control" value="{{$coupon->quantity}}" name="quantity">
                                            </div>
                                        </div>

                                    </div>



                                    <button type="submit" class="btn btn-default DirectionLtr" style="float:left; width: 120px; text-align: center !important;" >שלח קופון</button>
                                    {{csrf_field()}}
                                </form>
                            </div>
                            <!-- /.col-lg-6 (nested) -->
                        </div>
                        <!-- /.row (nested) -->
                    </div>
                    <!-- /.panel-body -->
                </div>
                <!-- /.panel -->
            </div>
            <!-- /.col-lg-12 -->
        </div>
        <!-- /.row -->
    </div>
    <!-- /#page-wrapper -->

    </div>
    <!-- /#wrapper -->

@endsection

resources/views/Categories/index.blade.php
@extends('layouts.app')

@section('content')

    <section id="content">
        <div class="page page-full page-mail">
            <div class="tbox tbox-sm">

                <!-- ====================================================
                ================= Left Bar ===============================
                ===================================================== -->

                <!-- left side -->
                <div class="tcol w-md bg-tr-white lt b-r">

                    <!-- left side body -->
                    <div class="p-15 collapse collapse-xs collapse-sm" id="mail-nav">

                        <ul class="nav nav-pills nav-stacked nav-sm" id="mail-folders">
                            <li class="active"><a href="mail-inbox.html">Inbox <span class="pull-right badge bg-lightred">6</span></a></li>
                            <li><a href="javascript:;">Sent</a></li>
                            <li><a href="javascript:;">Draft</a></li>
                        </ul>

                        <h5 class="b-b p-10 text-strong">Labels</h5>
                        <ul class="nav nav-pills nav-stacked nav-sm" id="mail-labels">
                            <li><a href="javascript:;"><i class="fa fa-fw fa-circle text-primary"></i>Family</a></li>
                            <li><a href="javascript:;"><i class="fa fa-fw fa-circle text-default"></i>Work</a></li>
                        </ul>

                    </div>
                    <!-- /left side body -->
                </div>
                <!-- /left side -->


                <!-- ====================================================
               ================= Content ===============================
               ===================================================== -->

                <!-- right side -->
                <div class="tcol">
                    @if(count($Categories) == 0)
                        <div class="alert alert-warning alert-dismissable" style="direction:rtl; text-align:right;">
                            <strong>לא נמצאו ספקים , <a href="new_supplier.php"> לחצ/י כאן</a> כדי להוסיף ספק.</strong>
                        </div>
                    @endif
                    <div class="p-15 bg-white b-b">

                        <div class="btn-group pull-right">
                            <button type="button" class="btn btn-default">צור קטגורייה חדשה</button>
                        </div>
                        <div class="btn-toolbar">
                        </div>
                    </div>
                        {{$Categories}}
                    <ul class="list-group no-radius no-border" id="mails-list">


                        @foreach($Categories as $item)

                            <li class="list-group-item b-primary" style="direction:rtl; text-align:right;">
                                <div class="media">
                                    <div class="pull-right">
                                        <div class="thumb thumb-sm" style="width:65px;">
                                            <a href=""><img class="img-circle" style="height:65px !important; width:65px !important" border="0" src="{{$item->media1}}"></a>
                                        </div>
                                    </div>
                                    <div class="media-body">
                                        <div class="media-heading m-0">
                                            <a href="" class="mr-1">{{$item->title}}</a>
                                            <span class="pull-left text-sm text-muted" >
                                                <div class="hidden-xs" style="margin-top:5px;">
                                                    <a href="/company_categories/{{$item->id}}/companies" >
                                                        <button  class="btn btn-primary btn-ef btn-ef-7 btn-ef-7b mb-10" style="font-weight:bold; direction:rtl; background-color:#0C3;">
                                                            <span class="badge bg-lightred" style="margin-right:4px;">{{ count($item->companies) }} </span> מספר עסקים<i class="glyphicon glyphicon-gift" style="padding-top:5px; "></i>
                                                        </button>
                                                    </a>
                                                    <a href="">
                                                        <button  class="btn btn-primary btn-ef btn-ef-7 btn-ef-7b mb-10" style="font-weight:bold; direction:rtl; background-color:#666">ערוך קטגורייה
                                                            <i class="glyphicon glyphicon-edit" style="padding-top:5px;  "></i>
                                                        </button>
                                                    </a>
                                                    <button onClick="" class="btn btn-primary btn-ef btn-ef-7 btn-ef-7b mb-10" style="font-weight:bold; direction:rtl">מחיקת קטגורייה
                                                        <i class="glyphicon glyphicon-trash" style="padding-top:5px; "></i>
                                                    </button>
                                                </div>
                                            </span>
                                        </div>
                                        <div>{{$item->title}}</div>
                                    </div>
                                </div>
                            </li>

                        @endforeach
                    </ul>
                    <!-- / mails -->
                    <!-- /right side body -->
                </div>
                <!-- /right side -->
            </div>
        </div>
    </section>
    <!--/ CONTENT -->
@endsection